[openweathermap]
api_key = "111fe49b8e6d3a5bf64e8a08c38574c7"

[mongodb]
uri = "mongodb+srv://adewaleogabi:Bosedefemi3#@smartenergycluster.0i58wyd.mongodb.net/?retryWrites=true&w=majority&appName=SmartEnergyCluster"
